baseURL: "https://kanebetter.github.io/"
title: Kane
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

googleAnalytics: G-MRV0T2HZ0C

minify:
  disableXML: true
  minifyOutput: true

params:


  disqusShortname: yourDisqusShortname
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Kane
  description: "Share what I see and make friends"
  keywords: [Blog, Portfolio]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/assets/images/favicon.ico"
    favicon16x16: "/assets/images/favicon-16x16.png"
    favicon32x32: "/assets/images/favicon-32x32.png"
    apple_touch_icon: "/assets/images/apple-touch-icon.png"
    safari_pinned_tab: "/assets/images/apple-touch-icon.png"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/TonyLovrChen"
    - name: spotify
      url: "https://open.spotify.com/user/21zcpsceeybeaib5xx2bn2pda"
    - name: youtube
      url: "https://www.youtube.com/channel/UCdo8CzknFdiWYvk9423f-OQ"
    #- name: stackoverflow
    #  url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/kanebetter"

  analytics:
    google:
      SiteVerificationTag: "G-MRV0T2HZ0C"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/KaneBetter/KaneBetter.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: notion
      name: Notion
      url: https://kaiqinc.notion.site/
      weight: 30
    - identifier: about
      name: About
      url: https://kanebetter.github.io/resume/
      weight: 40
outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary
taxonomies:
  category: categories
  tag: tags
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai